# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AccessCodesCreateResponseAccessCodeStatus(str, enum.Enum):
    SETTING = "setting"
    SET = "set"
    UNSET = "unset"
    REMOVING = "removing"
    UNKNOWN = "unknown"

    def visit(
        self,
        setting: typing.Callable[[], T_Result],
        set: typing.Callable[[], T_Result],
        unset: typing.Callable[[], T_Result],
        removing: typing.Callable[[], T_Result],
        unknown: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is AccessCodesCreateResponseAccessCodeStatus.SETTING:
            return setting()
        if self is AccessCodesCreateResponseAccessCodeStatus.SET:
            return set()
        if self is AccessCodesCreateResponseAccessCodeStatus.UNSET:
            return unset()
        if self is AccessCodesCreateResponseAccessCodeStatus.REMOVING:
            return removing()
        if self is AccessCodesCreateResponseAccessCodeStatus.UNKNOWN:
            return unknown()
