# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AccessCodesUpdatePutRequestType(str, enum.Enum):
    ONGOING = "ongoing"
    TIME_BOUND = "time_bound"

    def visit(self, ongoing: typing.Callable[[], T_Result], time_bound: typing.Callable[[], T_Result]) -> T_Result:
        if self is AccessCodesUpdatePutRequestType.ONGOING:
            return ongoing()
        if self is AccessCodesUpdatePutRequestType.TIME_BOUND:
            return time_bound()
