# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .access_codes_update_put_response_action_attempt_error import AccessCodesUpdatePutResponseActionAttemptError
from .access_codes_update_put_response_action_attempt_pending import AccessCodesUpdatePutResponseActionAttemptPending
from .access_codes_update_put_response_action_attempt_success import AccessCodesUpdatePutResponseActionAttemptSuccess


class AccessCodesUpdatePutResponseActionAttempt_Success(AccessCodesUpdatePutResponseActionAttemptSuccess):
    status: typing_extensions.Literal["success"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AccessCodesUpdatePutResponseActionAttempt_Pending(AccessCodesUpdatePutResponseActionAttemptPending):
    status: typing_extensions.Literal["pending"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class AccessCodesUpdatePutResponseActionAttempt_Error(AccessCodesUpdatePutResponseActionAttemptError):
    status: typing_extensions.Literal["error"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


AccessCodesUpdatePutResponseActionAttempt = typing.Union[
    AccessCodesUpdatePutResponseActionAttempt_Success,
    AccessCodesUpdatePutResponseActionAttempt_Pending,
    AccessCodesUpdatePutResponseActionAttempt_Error,
]
