# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

AccessCodesSimulateCreateUnmanagedAccessCodeResponseAccessCodeTimeBoundCreatedAt = typing.Union[str, dt.datetime]
