# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .action_attempt_error import ActionAttemptError
from .action_attempt_pending import ActionAttemptPending
from .action_attempt_success import ActionAttemptSuccess


class ActionAttempt_Success(ActionAttemptSuccess):
    status: typing_extensions.Literal["success"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ActionAttempt_Pending(ActionAttemptPending):
    status: typing_extensions.Literal["pending"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ActionAttempt_Error(ActionAttemptError):
    status: typing_extensions.Literal["error"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


ActionAttempt = typing.Union[ActionAttempt_Success, ActionAttempt_Pending, ActionAttempt_Error]
