# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .action_attempts_get_response_action_attempt_error import ActionAttemptsGetResponseActionAttemptError
from .action_attempts_get_response_action_attempt_pending import ActionAttemptsGetResponseActionAttemptPending
from .action_attempts_get_response_action_attempt_success import ActionAttemptsGetResponseActionAttemptSuccess


class ActionAttemptsGetResponseActionAttempt_Success(ActionAttemptsGetResponseActionAttemptSuccess):
    status: typing_extensions.Literal["success"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ActionAttemptsGetResponseActionAttempt_Pending(ActionAttemptsGetResponseActionAttemptPending):
    status: typing_extensions.Literal["pending"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class ActionAttemptsGetResponseActionAttempt_Error(ActionAttemptsGetResponseActionAttemptError):
    status: typing_extensions.Literal["error"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


ActionAttemptsGetResponseActionAttempt = typing.Union[
    ActionAttemptsGetResponseActionAttempt_Success,
    ActionAttemptsGetResponseActionAttempt_Pending,
    ActionAttemptsGetResponseActionAttempt_Error,
]
