# This file was auto-generated by Fern from our API Definition.

import typing

from .connected_accounts_get_request_connected_accounts_get_request import (
    ConnectedAccountsGetRequestConnectedAccountsGetRequest,
)

ConnectedAccountsGetRequest = typing.Union[
    ConnectedAccountsGetRequestConnectedAccountsGetRequest, ConnectedAccountsGetRequestConnectedAccountsGetRequest
]
