# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConnectWebviewsCreateRequestAcceptedProvidersItem(str, enum.Enum):
    AKUVOX = "akuvox"
    AUGUST = "august"
    AVIGILON_ALTA = "avigilon_alta"
    BRIVO = "brivo"
    BUTTERFLYMX = "butterflymx"
    SCHLAGE = "schlage"
    SMARTTHINGS = "smartthings"
    YALE = "yale"
    GENIE = "genie"
    DOORKING = "doorking"
    SALTO = "salto"
    LOCKLY = "lockly"
    TTLOCK = "ttlock"
    LINEAR = "linear"
    NOISEAWARE = "noiseaware"
    NUKI = "nuki"
    SEAM_RELAY_ADMIN = "seam_relay_admin"
    IGLOO = "igloo"
    KWIKSET = "kwikset"
    MINUT = "minut"
    MY_2_N = "my_2n"
    CONTROLBYWEB = "controlbyweb"
    NEST = "nest"
    IGLOOHOME = "igloohome"
    ECOBEE = "ecobee"
    HUBITAT = "hubitat"
    YALE_ACCESS = "yale_access"

    def visit(
        self,
        akuvox: typing.Callable[[], T_Result],
        august: typing.Callable[[], T_Result],
        avigilon_alta: typing.Callable[[], T_Result],
        brivo: typing.Callable[[], T_Result],
        butterflymx: typing.Callable[[], T_Result],
        schlage: typing.Callable[[], T_Result],
        smartthings: typing.Callable[[], T_Result],
        yale: typing.Callable[[], T_Result],
        genie: typing.Callable[[], T_Result],
        doorking: typing.Callable[[], T_Result],
        salto: typing.Callable[[], T_Result],
        lockly: typing.Callable[[], T_Result],
        ttlock: typing.Callable[[], T_Result],
        linear: typing.Callable[[], T_Result],
        noiseaware: typing.Callable[[], T_Result],
        nuki: typing.Callable[[], T_Result],
        seam_relay_admin: typing.Callable[[], T_Result],
        igloo: typing.Callable[[], T_Result],
        kwikset: typing.Callable[[], T_Result],
        minut: typing.Callable[[], T_Result],
        my_2_n: typing.Callable[[], T_Result],
        controlbyweb: typing.Callable[[], T_Result],
        nest: typing.Callable[[], T_Result],
        igloohome: typing.Callable[[], T_Result],
        ecobee: typing.Callable[[], T_Result],
        hubitat: typing.Callable[[], T_Result],
        yale_access: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.AKUVOX:
            return akuvox()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.AUGUST:
            return august()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.AVIGILON_ALTA:
            return avigilon_alta()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.BRIVO:
            return brivo()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.BUTTERFLYMX:
            return butterflymx()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.SCHLAGE:
            return schlage()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.SMARTTHINGS:
            return smartthings()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.YALE:
            return yale()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.GENIE:
            return genie()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.DOORKING:
            return doorking()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.SALTO:
            return salto()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.LOCKLY:
            return lockly()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.TTLOCK:
            return ttlock()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.LINEAR:
            return linear()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.NOISEAWARE:
            return noiseaware()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.NUKI:
            return nuki()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.SEAM_RELAY_ADMIN:
            return seam_relay_admin()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.IGLOO:
            return igloo()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.KWIKSET:
            return kwikset()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.MINUT:
            return minut()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.MY_2_N:
            return my_2_n()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.CONTROLBYWEB:
            return controlbyweb()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.NEST:
            return nest()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.IGLOOHOME:
            return igloohome()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.ECOBEE:
            return ecobee()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.HUBITAT:
            return hubitat()
        if self is ConnectWebviewsCreateRequestAcceptedProvidersItem.YALE_ACCESS:
            return yale_access()
