# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConnectWebviewsCreateRequestProviderCategory(str, enum.Enum):
    STABLE = "stable"
    CONSUMER_SMARTLOCKS = "consumer_smartlocks"
    INTERNAL_BETA = "internal_beta"

    def visit(
        self,
        stable: typing.Callable[[], T_Result],
        consumer_smartlocks: typing.Callable[[], T_Result],
        internal_beta: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ConnectWebviewsCreateRequestProviderCategory.STABLE:
            return stable()
        if self is ConnectWebviewsCreateRequestProviderCategory.CONSUMER_SMARTLOCKS:
            return consumer_smartlocks()
        if self is ConnectWebviewsCreateRequestProviderCategory.INTERNAL_BETA:
            return internal_beta()
