# This file was auto-generated by Fern from our API Definition.

import typing

from .devices_list_request_device_types_item_devices_list_request_device_types_item import (
    DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem,
)

DevicesListRequestDeviceTypesItem = typing.Union[
    DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem,
    DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem,
    DevicesListRequestDeviceTypesItemDevicesListRequestDeviceTypesItem,
]
