# This file was auto-generated by Fern from our API Definition.

import typing

from .device_device_type_device_device_type import DeviceDeviceTypeDeviceDeviceType

DeviceDeviceType = typing.Union[
    DeviceDeviceTypeDeviceDeviceType, DeviceDeviceTypeDeviceDeviceType, DeviceDeviceTypeDeviceDeviceType
]
