# This file was auto-generated by Fern from our API Definition.

import typing

from .devices_unmanaged_list_request_device_type_devices_unmanaged_list_request_device_type import (
    DevicesUnmanagedListRequestDeviceTypeDevicesUnmanagedListRequestDeviceType,
)

DevicesUnmanagedListRequestDeviceType = typing.Union[
    DevicesUnmanagedListRequestDeviceTypeDevicesUnmanagedListRequestDeviceType,
    DevicesUnmanagedListRequestDeviceTypeDevicesUnmanagedListRequestDeviceType,
    DevicesUnmanagedListRequestDeviceTypeDevicesUnmanagedListRequestDeviceType,
]
