# This file was auto-generated by Fern from our API Definition.

import typing

from .devices_list_request_device_type_devices_list_request_device_type import (
    DevicesListRequestDeviceTypeDevicesListRequestDeviceType,
)

DevicesListRequestDeviceType = typing.Union[
    DevicesListRequestDeviceTypeDevicesListRequestDeviceType,
    DevicesListRequestDeviceTypeDevicesListRequestDeviceType,
    DevicesListRequestDeviceTypeDevicesListRequestDeviceType,
]
