# This file was auto-generated by Fern from our API Definition.

import typing

from .locks_list_request_device_types_item_locks_list_request_device_types_item import (
    LocksListRequestDeviceTypesItemLocksListRequestDeviceTypesItem,
)

LocksListRequestDeviceTypesItem = typing.Union[
    LocksListRequestDeviceTypesItemLocksListRequestDeviceTypesItem,
    LocksListRequestDeviceTypesItemLocksListRequestDeviceTypesItem,
    LocksListRequestDeviceTypesItemLocksListRequestDeviceTypesItem,
]
