# This file was auto-generated by Fern from our API Definition.

import typing

from .locks_list_request_device_type_locks_list_request_device_type import (
    LocksListRequestDeviceTypeLocksListRequestDeviceType,
)

LocksListRequestDeviceType = typing.Union[
    LocksListRequestDeviceTypeLocksListRequestDeviceType,
    LocksListRequestDeviceTypeLocksListRequestDeviceType,
    LocksListRequestDeviceTypeLocksListRequestDeviceType,
]
