# This file was auto-generated by Fern from our API Definition.

import typing

from .thermostats_list_request_device_type_thermostats_list_request_device_type import (
    ThermostatsListRequestDeviceTypeThermostatsListRequestDeviceType,
)

ThermostatsListRequestDeviceType = typing.Union[
    ThermostatsListRequestDeviceTypeThermostatsListRequestDeviceType,
    ThermostatsListRequestDeviceTypeThermostatsListRequestDeviceType,
    ThermostatsListRequestDeviceTypeThermostatsListRequestDeviceType,
]
