# This file was auto-generated by Fern from our API Definition.

import typing

from .unmanaged_device_device_type_unmanaged_device_device_type import (
    UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType,
)

UnmanagedDeviceDeviceType = typing.Union[
    UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType,
    UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType,
    UnmanagedDeviceDeviceTypeUnmanagedDeviceDeviceType,
]
