# This file was auto-generated by Fern from our API Definition.

from .environment import SeamEnvironment
from .resources.access_codes.client import AccessCodesClient, AsyncAccessCodesClient
from .resources.action_attempts.client import ActionAttemptsClient, AsyncActionAttemptsClient


class Seam:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.DEFAULT, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AccessCodesClient(environment=self._environment, token=self._token)
        self.action_attempts = ActionAttemptsClient(environment=self._environment, token=self._token)


class AsyncSeam:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.DEFAULT, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AsyncAccessCodesClient(environment=self._environment, token=self._token)
        self.action_attempts = AsyncActionAttemptsClient(environment=self._environment, token=self._token)
