# This file was auto-generated by Fern from our API Definition.

from .environment import SeamEnvironment
from .resources.access_codes.client import AccessCodesClient, AsyncAccessCodesClient


class Seam:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.PRODUCTION, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AccessCodesClient(environment=self._environment, token=self._token)


class AsyncSeam:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.PRODUCTION, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AsyncAccessCodesClient(environment=self._environment, token=self._token)
