# This file was auto-generated by Fern from our API Definition.

from .environment import SeamApiEnvironment
from .resources.access_codes.client import AccessCodesClient, AsyncAccessCodesClient


class SeamApi:
    def __init__(self, *, environment: SeamApiEnvironment = SeamApiEnvironment.PRODUCTION, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AccessCodesClient(environment=self._environment, token=self._token)


class AsyncSeamApi:
    def __init__(self, *, environment: SeamApiEnvironment = SeamApiEnvironment.PRODUCTION, token: str):
        self._environment = environment
        self._token = token
        self.access_codes = AsyncAccessCodesClient(environment=self._environment, token=self._token)
