# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...environment import SeamEnvironment
from .resources.noise_thresholds.client import AsyncNoiseThresholdsClient, NoiseThresholdsClient
from .resources.simulate.client import AsyncSimulateClient, SimulateClient


class NoiseSensorsClient:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.DEFAULT, client_wrapper: SyncClientWrapper):
        self._environment = environment
        self._client_wrapper = client_wrapper
        self.simulate = SimulateClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.noise_thresholds = NoiseThresholdsClient(
            environment=self._environment, client_wrapper=self._client_wrapper
        )


class AsyncNoiseSensorsClient:
    def __init__(self, *, environment: SeamEnvironment = SeamEnvironment.DEFAULT, client_wrapper: AsyncClientWrapper):
        self._environment = environment
        self._client_wrapper = client_wrapper
        self.simulate = AsyncSimulateClient(environment=self._environment, client_wrapper=self._client_wrapper)
        self.noise_thresholds = AsyncNoiseThresholdsClient(
            environment=self._environment, client_wrapper=self._client_wrapper
        )
