# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AccessCodesCreateMultipleRequestBehaviorWhenCodeCannotBeShared(str, enum.Enum):
    THROW = "throw"
    CREATE_RANDOM_CODE = "create_random_code"

    def visit(
        self, throw: typing.Callable[[], T_Result], create_random_code: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is AccessCodesCreateMultipleRequestBehaviorWhenCodeCannotBeShared.THROW:
            return throw()
        if self is AccessCodesCreateMultipleRequestBehaviorWhenCodeCannotBeShared.CREATE_RANDOM_CODE:
            return create_random_code()
