# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClimateSettingSchedulesUpdateRequestHvacModeSetting(str, enum.Enum):
    OFF = "off"
    HEAT = "heat"
    COOL = "cool"
    HEATCOOL = "heatcool"

    def visit(
        self,
        off: typing.Callable[[], T_Result],
        heat: typing.Callable[[], T_Result],
        cool: typing.Callable[[], T_Result],
        heatcool: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClimateSettingSchedulesUpdateRequestHvacModeSetting.OFF:
            return off()
        if self is ClimateSettingSchedulesUpdateRequestHvacModeSetting.HEAT:
            return heat()
        if self is ClimateSettingSchedulesUpdateRequestHvacModeSetting.COOL:
            return cool()
        if self is ClimateSettingSchedulesUpdateRequestHvacModeSetting.HEATCOOL:
            return heatcool()
