# This file was auto-generated by Fern from our API Definition.

import typing

from .connected_accounts_get_request_connected_account_id import ConnectedAccountsGetRequestConnectedAccountId
from .connected_accounts_get_request_email import ConnectedAccountsGetRequestEmail

ConnectedAccountsGetRequest = typing.Union[
    ConnectedAccountsGetRequestConnectedAccountId, ConnectedAccountsGetRequestEmail
]
