# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConnectWebviewStatus(str, enum.Enum):
    PENDING = "pending"
    FAILED = "failed"
    AUTHORIZED = "authorized"

    def visit(
        self,
        pending: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
        authorized: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ConnectWebviewStatus.PENDING:
            return pending()
        if self is ConnectWebviewStatus.FAILED:
            return failed()
        if self is ConnectWebviewStatus.AUTHORIZED:
            return authorized()
