# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DevicesListDeviceProvidersResponseDeviceProvidersItemProviderCategoriesItem(str, enum.Enum):
    STABLE = "stable"
    CONSUMER_SMARTLOCKS = "consumer_smartlocks"

    def visit(
        self, stable: typing.Callable[[], T_Result], consumer_smartlocks: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is DevicesListDeviceProvidersResponseDeviceProvidersItemProviderCategoriesItem.STABLE:
            return stable()
        if self is DevicesListDeviceProvidersResponseDeviceProvidersItemProviderCategoriesItem.CONSUMER_SMARTLOCKS:
            return consumer_smartlocks()
