# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .simulate_create_unmanaged_access_code_response_access_code_ongoing import (
    SimulateCreateUnmanagedAccessCodeResponseAccessCodeOngoing,
)
from .simulate_create_unmanaged_access_code_response_access_code_time_bound import (
    SimulateCreateUnmanagedAccessCodeResponseAccessCodeTimeBound,
)


class SimulateCreateUnmanagedAccessCodeResponseAccessCode_Ongoing(
    SimulateCreateUnmanagedAccessCodeResponseAccessCodeOngoing
):
    type: typing_extensions.Literal["ongoing"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


class SimulateCreateUnmanagedAccessCodeResponseAccessCode_TimeBound(
    SimulateCreateUnmanagedAccessCodeResponseAccessCodeTimeBound
):
    type: typing_extensions.Literal["time_bound"]

    class Config:
        frozen = True
        allow_population_by_field_name = True


SimulateCreateUnmanagedAccessCodeResponseAccessCode = typing.Union[
    SimulateCreateUnmanagedAccessCodeResponseAccessCode_Ongoing,
    SimulateCreateUnmanagedAccessCodeResponseAccessCode_TimeBound,
]
