# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions

from ..core.datetime_utils import serialize_datetime
from .simulate_create_unmanaged_access_code_response_access_code_ongoing_created_at import (
    SimulateCreateUnmanagedAccessCodeResponseAccessCodeOngoingCreatedAt,
)


class SimulateCreateUnmanagedAccessCodeResponseAccessCodeOngoing(pydantic.BaseModel):
    access_code_id: str
    code: typing.Optional[str]
    status: typing_extensions.Literal["set"]
    created_at: SimulateCreateUnmanagedAccessCodeResponseAccessCodeOngoingCreatedAt
    is_managed: str
    starts_at: typing.Optional[str]
    ends_at: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
