# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UnmanagedListResponseAccessCodesItemType(str, enum.Enum):
    TIME_BOUND = "time_bound"
    ONGOING = "ongoing"

    def visit(self, time_bound: typing.Callable[[], T_Result], ongoing: typing.Callable[[], T_Result]) -> T_Result:
        if self is UnmanagedListResponseAccessCodesItemType.TIME_BOUND:
            return time_bound()
        if self is UnmanagedListResponseAccessCodesItemType.ONGOING:
            return ongoing()
