# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.noise_thresholds.client import AsyncNoiseThresholdsClient, NoiseThresholdsClient
from .resources.simulate.client import AsyncSimulateClient, SimulateClient


class NoiseSensorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.simulate = SimulateClient(client_wrapper=self._client_wrapper)
        self.noise_thresholds = NoiseThresholdsClient(client_wrapper=self._client_wrapper)


class AsyncNoiseSensorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.simulate = AsyncSimulateClient(client_wrapper=self._client_wrapper)
        self.noise_thresholds = AsyncNoiseThresholdsClient(client_wrapper=self._client_wrapper)
